; Super Mario Bros. 3 Full Disassembly by Southbird 2012
; For more info, see http://www.sonicepoch.com/sm3mix/
;
; PLEASE INCLUDE A CREDIT TO THE SOUTHBIRD DISASSEMBLY
; AND THE ABOVE LINK SOMEWHERE IN YOUR WORKS :)
;
; Original disassembler source generated by DCC6502 version v1.4
; (With labels, comments, and some syntax corrections for nesasm by Southbird)
; For more info about DCC6502, e-mail veilleux@ameth.org
;
; This source file last updated: 2011-11-18 21:50:36.000000000 -0600
; Distribution package date: Fri Apr  6 23:46:16 UTC 2012

.include "../inc/macros.inc"
.include "../inc/defines.inc"

; exports
.export BigQBlock1O, BigQBlock2O, BigQBlock3O, BigQBlock4O, BigQBlock5O, BigQBlock6O, BigQBlock7O, BigQBlock8O, CoinShipO
.export CoinShip_BossO, Empty_ObjLayout, KINGO, TOADO, TOAD_SpecO, Unused2_ExitO, Unused3O, Unused3_CHO, Unused4_InnerO
.export Unused7_EndO, Unused8_EndO, W101O, W102O, W103O, W103_CoinHeavO, W104O, W104_EndO, W105O, W105_CoinHeavO, W106O
.export W10FO, W10F_AltO, W1AirshipO, W1Airship_BossO, W1HBO, W1UNO, W201O, W202O, W202_ExitO, W203O, W203_ExitO, W204O, W205O
.export W20FO, W20F_AltO, W2AirshipO, W2Airship_BossO, W2FBO, W2HBO, W2P1O, W2PYO, W2PY_InsideO, W2STO, W301O, W301_ExitO
.export W302O, W302_EndO, W303O, W303_EndO, W304O, W305O, W305_EndO, W306O, W306_EndO, W307O, W307_CoinHeavO, W308O, W309O, W309_EndO
.export W3AirshipO, W3Airship_BossO, W3F1O, W3F1_AltO, W3F2O, W3F2_AltO, W3HBO, W3P1O, W3P2O, W3P3O, W401O, W401_BonusO, W402O
.export W403O, W403_UnderO, W404O, W405O, W405_BonusO, W40F_BonusO, W46AO, W46BO, W4AirshipO, W4Airship_BossO, W4F1O, W4F2O
.export W4F2_BonusO, W4HBO, W4P1O, W4P2O, W501O, W501_BonusO, W502O, W502_UnderO, W503O, W503_EndO, W503_InsideO, W504O, W504_EndO
.export W505O, W506O, W507O, W507_LowerO, W508O, W509O, W5AirshipO, W5Airship_BossO, W5F1O, W5F1_AltO, W5F2O, W5F2_AltO, W5P1O
.export W5T1O, W5T2O, W5T3O, W5T4O, W5TDO, W601O, W602O, W602_EndO, W603O, W604O, W604_CoinHeavO, W605O, W605_UnderO, W606O, W606_UnderO
.export W607O, W607_EndO, W608O, W609O, W609_UnderO, W610O, W6AirshipO, W6Airship_BossO, W6F1O, W6F1_AltO, W6F2O, W6F2_AltO
.export W6F3O, W6F3_AltO, W6P1O, W6P2O, W701O, W701_MazeO, W702O, W703O, W704O, W704_WaterO, W705O, W705_UnderO, W706O, W706_MazeO
.export W707O, W707_MainO, W708O, W708_CoinHeavO, W709O, W709_EndO, W7AirshipO, W7Airship_BossO, W7F1O, W7F2O, W7F2_AltO
.export W7I1O, W7I1_PrizeO, W7I2O, W7I2_PrizeO, W7P1O, W7P2O, W7P3O, W7P4O, W7P5O, W7P6O, W7P7O, W7P8O, W801O, W802O, W80FO, W80F_AltO
.export W8AirshipO, W8Airship_BossO, W8BCO, W8BC_AltO, W8BSO, W8BS_BossO, W8H1O, W8H2O, W8H3O, W8HBO, W8H_PrizeO, W8P1O, W8P2O
.export W8P3O, W8P4O, W8P5O, W8P6O, W8T1O, W8T2O, W8Tank1_BossO, W8Tank2_BossO, WAirship_IntroO



.segment "PRG006"

_C000:		.include "objects/C000.asm"
W2UNO:		.include "objects/EmptyW2.asm"	; Unused/empty object set linked to World 2 Start Panel
_C004:		.include "objects/C004.asm"
W503O:
Empty_ObjLayout:	.include "objects/Empty.asm"	; Shared Empty object set
_C008:		.include "objects/C008.asm"
_C00A:		.include "objects/C00A.asm"
_C00C:		.include "objects/C00C.asm"
_C00E:		.include "objects/C00E.asm"
_C010:		.include "objects/C010.asm"
_C012:		.include "objects/C012.asm"
_C014:		.include "objects/C014.asm"
_C016:		.include "objects/C016.asm"
_C018:		.include "objects/C018.asm"
_C01A:		.include "objects/C01A.asm"
_C01C:		.include "objects/C01C.asm"
_C01E:		.include "objects/C01E.asm"
_C020:		.include "objects/C020.asm"
_C025:		.include "objects/C025.asm"
TOADO:		.include "objects/ToadTyp.asm"
TOAD_SpecO:	.include "objects/ToadSpec.asm"
W8HBO:		.include "objects/W8HBO.asm"	; World 8 Hammer Bro object mapping (sort of)
_C06F:		.include "objects/C06F.asm"
_C07A:		.include "objects/C07A.asm"
_C07C:		.include "objects/C07C.asm"
_C07E:		.include "objects/C07E.asm"
_C080:		.include "objects/C080.asm"
_C082:		.include "objects/C082.asm"
_C084:		.include "objects/C084.asm"
_C098:		.include "objects/C098.asm"
_C0A0:		.include "objects/C0A0.asm"
W8P1O:		.include "objects/W8Pipe1.asm"	; World 8 Pipe Junction 1
W8P2O:		.include "objects/W8Pipe2.asm"	; World 8 Pipe Junction 2
W8P3O:		.include "objects/W8Pipe3.asm"	; World 8 Pipe Junction 3
W8P4O:		.include "objects/W8Pipe4.asm"	; World 8 Pipe Junction 4
W8P5O:		.include "objects/W8Pipe5.asm"	; World 8 Pipe Junction 5
W8P6O:		.include "objects/W8Pipe6.asm"	; World 8 Pipe Junction 6
W7P1O:		.include "objects/W7Pipe1.asm"	; World 7 Pipe Junction 1
W7P2O:		.include "objects/W7Pipe2.asm"	; World 7 Pipe Junction 2
W7P3O:		.include "objects/W7Pipe3.asm"	; World 7 Pipe Junction 3
W7P4O:		.include "objects/W7Pipe4.asm"	; World 7 Pipe Junction 4
W7P5O:		.include "objects/W7Pipe5.asm"	; World 7 Pipe Junction 5
W7P6O:		.include "objects/W7Pipe6.asm"	; World 7 Pipe Junction 6
W7P7O:		.include "objects/W7Pipe7.asm"	; World 7 Pipe Junction 7
W7P8O:		.include "objects/W7Pipe8.asm"	; World 7 Pipe Junction 8
W6P1O:		.include "objects/W6Pipe1.asm"	; World 6 Pipe Junction 1
W6P2O:		.include "objects/W6Pipe2.asm"	; World 6 Pipe Junction 2
W2P1O:		.include "objects/W2Pipe1.asm"	; World 2 Pipe Junction 1
W3P1O:		.include "objects/W3Pipe1.asm"	; World 3 Pipe Junction 1
W3P2O:		.include "objects/W3Pipe2.asm"	; World 3 Pipe Junction 2
W3P3O:		.include "objects/W3Pipe3.asm"	; World 3 Pipe Junction 3
W4P1O:		.include "objects/W4Pipe1.asm"	; World 4 Pipe Junction 1
W4P2O:		.include "objects/W4Pipe2.asm"	; World 4 Pipe Junction 2
W5P1O:		.include "objects/W5Pipe1.asm"	; World 5 Pipe Junction 1
W507_LowerO:	.include "objects/5-7Lower.asm"
W705_UnderO:	.include "objects/7-5Under.asm"
_C1A6:		.include "objects/C1A6.asm"
Unused1O:	.include "objects/Unused1.asm"	; "Unused level 1"
W46BO:		.include "objects/4-6B.asm"	; 4-6B
Unused2O:	.include "objects/Unused2.asm"	; "Unused level 2"
W701O:		.include "objects/7-1.asm"	; 7-1
W707O:		.include "objects/7-7.asm"	; 7-7
W46AO:		.include "objects/4-6A.asm"	; 4-6A
W503_InsideO:	.include "objects/5-3Inner.asm"	; 5-3 Inside
W103O:		.include "objects/1-3.asm"	; 1-3
W305_EndO:	.include "objects/3-5End.asm"	; 3-5 Exit
W405_BonusO:	.include "objects/4-5Bonus.asm"	; 4-5 Bonus
W708O:		.include "objects/7-8.asm"	; 7-8
W309O:		.include "objects/3-9.asm"	; 3-9
W309_EndO:	.include "objects/3-9End.asm"	; 3-9 Exit
W706O:		.include "objects/7-6.asm"	; 7-6
W704O:		.include "objects/7-4.asm"	; 7-4
W501O:		.include "objects/5-1.asm"	; 5-1
W501_BonusO:	.include "objects/5-1Bonus.asm"	; 5-1 Bonus
_C41F:		.include "objects/C41F.asm"
W801O:		.include "objects/8-1.asm"	; 8-1
W307O:		.include "objects/3-7.asm"	; 3-7
W301_ExitO:	.include "objects/3-1Exit.asm"	; 3-1 Exit pipe
_C4B4:		.include "objects/C4B4.asm"
_C4EC:		.include "objects/C4EC.asm"
W101O:		.include "objects/1-1.asm"	; 1-1
W705O:		.include "objects/7-5.asm"
W308_EndO:	.include "objects/3-8End.asm"	; 3-8 Exit
W503_EndO:	.include "objects/5-3End.asm"
_C565:		.include "objects/C565.asm"
Unused2_ExitO:	.include "objects/Unused2E.asm"	; "Unused level 2" Exit
W104_EndO:	.include "objects/1-4End.asm"	; 1-4 End
_C58C:		.include "objects/C58C.asm"
W303O:		.include "objects/3-3.asm"	; 3-3
W303_EndO:	.include "objects/3-3End.asm"	; 3-3 End
W2PY_InsideO:	.include "objects/PyramidI.asm"	; Pyramid (Inside)
W605_UnderO:	.include "objects/6-5Under.asm"	; 6-5 Underground
W609_UnderO:	.include "objects/6-9Under.asm"	; 6-9 Underground
W3HBO:		.include "objects/W3HBO.asm"	; World 3 Hammer Bro Battle
W606_UnderO:	.include "objects/6-6Under.asm"	; 6-6 Underground
W102O:		.include "objects/1-2.asm"	; 1-2
Unused3O:	.include "objects/Unused3.asm"	; "Unused level 3"
W703O:		.include "objects/7-3.asm"	; 7-3
W1HBO:		.include "objects/W1HBO.asm"	; World 1 Hammer Bro Battle
_C733:		.include "objects/C733.asm"
_C759:		.include "objects/C759.asm"
_C764:		.include "objects/C764.asm"
_C77E:		.include "objects/C77E.asm"
Unused4_InnerO:	.include "objects/Unused4I.asm"
_C7EB:		.include "objects/C7EB.asm"
_C80B:		.include "objects/C80B.asm"
W2STO:		.include "objects/SandTrap.asm"	; World 2 Sand Trap
W403_UnderO:	.include "objects/4-3Under.asm"	; 4-3 Underground
W202O:		.include "objects/2-2.asm"	; 2-2
W502O:		.include "objects/5-2.asm"	; 5-2 (above ground)
W802O:		.include "objects/8-2.asm"	; 8-2
W105O:		.include "objects/1-5.asm"	; 1-5
W308O:		.include "objects/3-8.asm"	; 3-8
W40F_BonusO:	.include "objects/4-FBonus.asm"	; World 4 Fortress Bonus area
BigQBlock1O:	.include "objects/BigQ1.asm"	; World 1's Big [?] block area (empty)
BigQBlock2O:	.include "objects/BigQ2.asm"	; World 2's Big [?] block area
BigQBlock3O:	.include "objects/BigQ3.asm"	; World 3's Big [?] block area
BigQBlock4O:	.include "objects/BigQ4.asm"	; World 4's Big [?] block area
BigQBlock5O:	.include "objects/BigQ5.asm"	; World 5's Big [?] block area
BigQBlock6O:	.include "objects/BigQ6.asm"	; World 6's Big [?] block area
BigQBlock7O:	.include "objects/BigQ7.asm"	; World 7's Big [?] block area
BigQBlock8O:	.include "objects/BigQ8.asm"	; World 8's Big [?] block area
W304O:		.include "objects/3-4.asm"	; 3-4
W608O:		.include "objects/6-8.asm"	; 6-8
W302O:		.include "objects/3-2.asm"	; 3-2
W302_EndO:	.include "objects/3-2End.asm"	; 3-2 End
W306O:		.include "objects/3-6.asm"	; 3-6
W306_EndO:	.include "objects/3-6End.asm"	; 3-6 End
W603O:		.include "objects/6-3.asm"	; 6-3
W6F2O:		.include "objects/6-F2.asm"	; World 6 2nd Fortress
W6F2_AltO:	.include "objects/6-F2A.asm"	; World 6 2nd Fortress Alternate
W605O:		.include "objects/6-5.asm"	; 6-5
Unused11O:	.include "objects/Unused11.asm"	; "Unused level 11"
W505O:		.include "objects/5-5.asm"	; 5-5
Unused12:	.include "objects/Unused12.asm"	; "Unused level 12"
Unused13:	.include "objects/Unused13.asm"	; "Unused level 13"
W602O:		.include "objects/6-2.asm"	; 6-2
_CB8D:		.include "objects/CB8D.asm"
W601O:		.include "objects/6-1.asm"
W1UNO:		.include "objects/Unused6.asm"	; "Unused Level 6"
W602_EndO:	.include "objects/6-2End.asm"	; 6-2 End (also end of "Unused Level 6")
W106O:		.include "objects/1-6.asm"	; 1-6
W104O:		.include "objects/1-4.asm"	; 1-4
W604O:		.include "objects/6-4.asm"	; 6-4
Unused7O:	.include "objects/Unused7.asm"	; "Unused level 7"
Unused7_EndO:	.include "objects/Unused7E.asm"	; "Unused level 7" exit area
W606O:		.include "objects/6-6.asm"	; 6-6
W610O:		.include "objects/6-10.asm"	; 6-10
W607O:		.include "objects/6-7.asm"	; 6-7
W607_EndO:	.include "objects/6-7End.asm"	; 6-7 End
W609O:		.include "objects/6-9.asm"	; 6-9
W707_MainO:	.include "objects/7-7Main.asm"	; 7-7 main section
_CD55:		.include "objects/CD55.asm"
W701_MazeO:	.include "objects/7-1Maze.asm"	; 7-1 Maze area
W704_WaterO:	.include "objects/7-4Water.asm"	; 7-4 Underwater section
W305O:		.include "objects/3-5.asm"	; 3-5
W4F2_BonusO:	.include "objects/4-F2Bonu.asm"	; World 4 2nd Fortress bonus
W301O:		.include "objects/3-1.asm"	; 3-1
W502_UnderO:	.include "objects/5-2Under.asm"	; 5-2 Underground
W706_MazeO:	.include "objects/7-6Maze.asm"	; 7-6 Maze
W508O:		.include "objects/5-8.asm"	; 5-8
W504_EndO:	.include "objects/5-4End.asm"	; 5-4 Exit
W307_CoinHeavO:	.include "objects/W307Coin.asm"	; 3-7 Coin Heaven
W401O:		.include "objects/4-1.asm"	; 4-1
Unused9O:	.include "objects/Unused9.asm"	; "Unused level 9"
W507O:		.include "objects/5-7.asm"	; 5-7
W403O:		.include "objects/4-3.asm"	; 4-3
W402O:		.include "objects/4-2.asm"	; 4-2
W506O:		.include "objects/5-6.asm"	; 5-6
W509O:		.include "objects/5-9.asm"	; 5-9
W404O:		.include "objects/4-4.asm"	; 4-4
Unused3_CHO:	.include "objects/Un3Coin.asm"	; "Unused Level 3" coin heaven
W103_CoinHeavO:	.include "objects/W103Coin.asm"	; 1-3 Coin Heaven
W5TDO:		.include "objects/W5TowerD.asm"	; World 5 Tower coming downward
W5T4O:		.include "objects/W5Tower4.asm"	; World 5 Tower 4/4
W5T2O:		.include "objects/W5Tower2.asm"	; World 5 Tower 2/4
W405O:		.include "objects/4-5.asm"	; 4-5
W604_CoinHeavO:	.include "objects/W604Coin.asm"	; 6-4 Coin Heaven
W105_CoinHeavO:	.include "objects/W105Coin.asm"	; 1-5 Coin Heaven
W401_BonusO:	.include "objects/4-1Bonus.asm"	; 4-1 Bonus
W504O:		.include "objects/5-4.asm"	; 5-4
W7I2O:		.include "objects/W7Plant2.asm"	; World 7 Giant Piranha 2
W7I1O:		.include "objects/W7Plant1.asm"	; World 7 Giant Piranha 1
W8H2O:		.include "objects/W8HTrap2.asm"	; World Hand Trap 2
W8H1O:		.include "objects/W8HTrap1.asm"	; World Hand Trap 1
W8H3O:		.include "objects/W8HTrap3.asm"	; World Hand Trap 3
W8H_PrizeO:	.include "objects/W8HTrapE.asm"	; World Hand Trap Prize room
W7I2_PrizeO:	.include "objects/W7Prize2.asm"	; World 7 Giant Piranha 2 Prize room
W7I1_PrizeO:	.include "objects/W7Prize1.asm"	; World 7 Giant Piranha 1 Prize room
W4HBO:		.include "objects/W4HBO.asm"	; World 4 Heavy Bro battle
W708_CoinHeavO:	.include "objects/W708Coin.asm"	; 7-8 Coin Heaven
W2PYO:		.include "objects/PyramidO.asm"	; Pyramid (outside)
W709_EndO:	.include "objects/7-9End.asm"	; 7-9 Exit
W702O:		.include "objects/7-2.asm"	; 7-2
W2FBO:		.include "objects/W2FBO.asm"	; World 2 Fire Bro
W2HBO:		.include "objects/W2HBO.asm"	; World 2 Boomerang Bro
Unused8_EndO:	.include "objects/Unused8E.asm"	; "Unused level 8" exit area
W709O:		.include "objects/7-9.asm"	; 7-9
W201O:		.include "objects/2-1.asm"	; 2-1
W205O:		.include "objects/2-5.asm"	; 2-5
W203O:		.include "objects/2-3.asm"	; 2-3
W20FO:		.include "objects/2-F.asm"	; World 2 Fortress
W20F_AltO:	.include "objects/2-FA.asm"	; World 2 Fortress Alternate
W204O:		.include "objects/2-4.asm"	; 2-4
_D28E:		.include "objects/D28E.asm"
W202_ExitO:	.include "objects/2-2Exit.asm"	; 2-2 Exit
W203_ExitO:	.include "objects/2-3Exit.asm"	; 2-3 Exit
KINGO:		.include "objects/King.asm"
W5F2O:		.include "objects/5-F2.asm"
W5F2_AltO:	.include "objects/5-F2A.asm"
_D309:		.include "objects/D309.asm"
_D320:		.include "objects/D320.asm"
W10FO:		.include "objects/1-F.asm"	; World 1 Fortress
W10F_AltO:	.include "objects/1-FA.asm"	; World 1 Fortress Alternate
W3F2O:		.include "objects/3-F2.asm"	; World 3 2nd Fortress
W3F2_AltO:	.include "objects/3-F2A.asm"	; World 3 2nd Fortress Alternate
W3F1O:		.include "objects/3-F1.asm"	; World 3 1st Fortress
W3F1_AltO:	.include "objects/3-F1A.asm"	; World 3 1st Fortress Alternate
W5F1O:		.include "objects/5-F1.asm"	; World 5 Ground Fortress
W5F1_AltO:	.include "objects/5-F1A.asm"	; World 5 Ground Fortress Alternate
Unused5O:	.include "objects/Unused5.asm"	; "Unused Level 5" (TCRF)
W7F2O:		.include "objects/7-F2.asm"	; World 7 2nd Fortress
W7F2_AltO:	.include "objects/7-F2A.asm"	; World 7 2nd Fortress Alternate
W6F3O:		.include "objects/6-F3.asm"	; World 6 3rd Fortress
W6F3_AltO:	.include "objects/6-F3A.asm"	; World 6 3rd Fortress Alternate
W6F1O:		.include "objects/6-F1.asm"	; World 6 1st Fortress
W6F1_AltO:	.include "objects/6-F1A.asm"	; World 6 1st Fortress Alternate
W7F1O:		.include "objects/7-F1.asm"	; World 7 1st Fortress
W5T1O:		.include "objects/W5Tower1.asm"
W5T3O:		.include "objects/W5Tower3.asm"
W4F2O:		.include "objects/4-F2.asm"
W4F1O:		.include "objects/4-F1.asm"
W80FO:		.include "objects/8-F.asm"
W80F_AltO:	.include "objects/8-FA.asm"
W8BCO:		.include "objects/Bowser.asm"
W8BC_AltO:	.include "objects/BowserA.asm"
_D637:		.include "objects/D637.asm"
WAirship_IntroO:	.include "objects/WAIntro.asm"	; Any Airship run, jump, catch anchor intro
W4Airship_BossO:	.include "objects/W4ABoss.asm"	; World 4 Airship boss room
W5AirshipO:	.include "objects/W5A.asm"			; World 5 Airship
W1AirshipO:	.include "objects/W1A.asm"			; World 1 Airship
W2AirshipO:	.include "objects/W2A.asm"			; World 2 Airship
W3AirshipO:	.include "objects/W3A.asm"			; World 3 Airship
W4AirshipO:	.include "objects/W4A.asm"			; World 4 Airship
W6AirshipO:	.include "objects/W6A.asm"			; World 6 Airship
W7AirshipO:	.include "objects/W7A.asm"			; World 7 Airship
W8AirshipO:	.include "objects/W8A.asm"			; World 8 Airship
W8BSO:		.include "objects/W8Ship.asm"		; World 8 Battleship
W8T2O:		.include "objects/W8Tank2.asm"		; World 8 Tank 2
W8T1O:		.include "objects/W8Tank1.asm"		; World 8 Tank 1
W1Airship_BossO:	.include "objects/W1ABoss.asm"	; World 1 Airship boss room
W2Airship_BossO:	.include "objects/W2ABoss.asm"	; World 2 Airship boss room
W3Airship_BossO:	.include "objects/W3ABoss.asm"	; World 3 Airship boss room
W5Airship_BossO:	.include "objects/W5ABoss.asm"	; World 5 Airship boss room
W6Airship_BossO:	.include "objects/W6ABoss.asm"	; World 6 Airship boss room
W7Airship_BossO:	.include "objects/W7ABoss.asm"	; World 7 Airship boss room
CoinShipO:		.include "objects/CoinShip.asm"	; Coin Ship
CoinShip_BossO:		.include "objects/CoinBoss.asm"	; Coin Ship boss
W8Tank2_BossO:		.include "objects/W8Tank2B.asm"
W8BS_BossO:		.include "objects/W8ShipBs.asm"
W8Airship_BossO:	.include "objects/W8ABoss.asm"	; World 8 Airship boss room
W8Tank1_BossO:	.include "objects/W8Tank1B.asm"
_DA34:		.include "objects/DA34.asm"
_DA60:		.include "objects/DA60.asm"
